[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = {
  DJANGO_SETTINGS_MODULE = "mystorelink.settings",
  PYTHONPATH = "/code"
}