[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT mystorelink.wsgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = {
  DJANGO_SETTINGS_MODULE = "mystorelink.settings",
  PYTHONPATH = "/app"
}