[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate && python manage.py create_superuser && python manage.py collectstatic --noinput && gunicorn mystorelink.wsgi:application --bind 0.0.0.0:$PORT"

[env]
DJANGO_SETTINGS_MODULE = "mystorelink.settings"
PYTHONPATH = "/code"