# Generated by Django 5.2.1 on 2025-06-04 11:57

import trackgrams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgrams', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='supabase_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=trackgrams.models.get_supabase_storage, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
