# Generated by Django 5.2.1 on 2025-06-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackgrams', '0004_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
    ]
