# Generated by Django 5.2.1 on 2025-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgrams', '0005_remove_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Food Entry', 'verbose_name_plural': 'Food Entries'},
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='calories_per_unit',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='total_calories',
            new_name='grams',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='unit',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
